### ISSUE TITLE
Premailer throwing error on build

### ISSUE THREAD

**Issue by jsakas** [jsakas/beatport-email-template#17]
Traceback (most recent call last):
  File "prototype.py", line 159, in <module>
    build(projectPath)
  File "prototype.py", line 86, in build
    genStaticFile(path, file, inliner = inliner)
  File "prototype.py", line 101, in genStaticFile
    html = pm.transform()
  File "/Library/Python/2.7/site-packages/premailer/premailer.py", line 226, in transform
    tree = etree.fromstring(stripped, parser).getroottree()
  File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70473)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106307)
  File "parser.pxi", line 1709, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105010)
  File "parser.pxi", line 1047, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:99438)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94254)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95690)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94969)
lxml.etree.XMLSyntaxError: None

**Comment by jsakas** [comment]
This was being caused by the macros template. It has been removed which resolves this error.
